### ISSUE TITLE
Improve devise pages (sign in, sign up, and similar pages)

### ISSUE THREAD

**Issue by lucascaton** [lucascaton/easy-lives#1]
Suggestion: use something like [this](https://dansup.github.io/bulma-templates/templates/login.html).

**Comment by frankyston** [comment]
Oi Lucas, vou implementar esse tela.

**Comment by frankyston** [comment]
Segue o Pull Request @lucascaton https://github.com/lucascaton/easy-lives/pull/3

**Comment by lucascaton** [comment]
Valeu @frankyston! 😄
